### ISSUE TITLE
Does not work with GSL 2.1

### ISSUE THREAD

**Issue by martin-ueding** [etmc/hadron#14]
Fedora ships with GSL 2.1. The `configure.ac` contains a snippet that assumes that it works with version `1.x`, this I have generalized in my fork. The version 2.x seems to have some API changes, so hadron does not compile any more:

```
gcc -m64 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -O3 -Wall -fpic  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic  -c gsl_fit.c -o gsl_fit.o
gsl_fit.c: In function 'multifit_cor':
gsl_fit.c:569:28: error: 'gsl_multifit_fdfsolver {aka struct <anonymous>}' has no member named 'J'
   gsl_multifit_covar(solver->J, 0.0, covar);
                            ^~
```

I guess support for 1.x and 2.x at the same time is not feasible?

**Comment by kostrzewa** [comment]
This is interesting, for me it still compiles even though I'm using gsl 2.1. I have https://github.com/urbach/hadron/commit/9ac1d3eef942624de6c2858436f033d3be4f64ca#commitcomment-22888592 in place so that the check passes.

**Comment by urbach** [comment]
> This is interesting, for me it still compiles even though I'm using gsl 2.1. I have https://github.com/urbach/hadron/commit/9ac1d3eef942624de6c2858436f033d3be4f64ca#commitcomment-22888592 in place so that the check passes.

for me it didn't compile anymore with GSL 1.X

> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/etmc/hadron/issues/14#issuecomment-312625656
--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by urbach** [comment]
> > This is interesting, for me it still compiles even though I'm using gsl 2.1. I have https://github.com/urbach/hadron/commit/9ac1d3eef942624de6c2858436f033d3be4f64ca#commitcomment-22888592 in place so that the check passes.
> 
> for me it didn't compile anymore with GSL 1.X

more precisely, it didn't configure anymore...

> 
> > 
> > -- 
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/etmc/hadron/issues/14#issuecomment-312625656
> --
> Carsten Urbach
> e-mail: curbach@gmx.de
>         urbach@hiskp.uni-bonn.de
> Fon   : +49 (0)228 73 2379
> skype : carsten.urbach
> URL: http://www.carsten-urbach.eu


--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by kostrzewa** [comment]
> more precisely, it didn't configure anymore...

This was due to a logic bug in 5ef79b2eeb9961cef422e19514d7ca50bb33e148, which https://github.com/urbach/hadron/commit/9ac1d3eef942624de6c2858436f033d3be4f64ca#commitcomment-22888592 corrects.

**Comment by martin-ueding** [comment]
I have just tried again with commit 33f62c68fb29f2dfea48ba779fd23cd5570539e4 and it still fails with the same error.

```spec
%global commit0 33f62c68fb29f2dfea48ba779fd23cd5570539e4
%global shortcommit0 %(c=%{commit0}; echo ${c:0:7})
%global packname hadron

Name:           R-%{packname}
Version:        1.0
Release:        1%{?dist}
Summary:        R package implementing analysis tools for lattice QCD

License:        GPL-3+
URL:            http://www.itkp.uni-bonn.de/~urbach/software.html
Source0:        https://github.com/urbach/%{packname}/archive/%{commit0}.tar.gz#/%{name}-%{shortcommit0}.tar.gz

BuildRequires:  gsl-devel R-devel tex(latex)
Requires:       gsl R-core

%description

%prep
%autosetup -n %{packname}-%{commit0}

%build
# R expects everything to be in a directory that has the name of the package.
# The TAR file from GitHub does not have this structure, so we make it here.
all=$(echo *); mkdir hadron; mv $all hadron/
cd hadron

autoconf
%configure

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{_libdir}/R/library
%{_bindir}/R CMD INSTALL -l $RPM_BUILD_ROOT%{_libdir}/R/library %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -rf $RPM_BUILD_ROOT%{_libdir}/R/library/R.css

%files
%doc

%changelog
```

And it still fails:

```
$ rpmbuild -ba R-hadron.spec 
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.acKoTC
+ umask 022
+ cd /home/mu/rpmbuild/BUILD
+ cd /home/mu/rpmbuild/BUILD
+ rm -rf hadron-33f62c68fb29f2dfea48ba779fd23cd5570539e4
+ /usr/bin/gzip -dc /home/mu/rpmbuild/SOURCES/R-hadron-33f62c6.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd hadron-33f62c68fb29f2dfea48ba779fd23cd5570539e4
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.l6KvVG
+ umask 022
+ cd /home/mu/rpmbuild/BUILD
+ cd hadron-33f62c68fb29f2dfea48ba779fd23cd5570539e4
++ echo DESCRIPTION NAMESPACE R README configure configure.ac data exec man src
+ all='DESCRIPTION NAMESPACE R README configure configure.ac data exec man src'
+ mkdir hadron
+ mv DESCRIPTION NAMESPACE R README configure configure.ac data exec man src hadron/
+ cd hadron
+ autoconf
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.XN1eDL
+ umask 022
+ cd /home/mu/rpmbuild/BUILD
+ '[' /home/mu/rpmbuild/BUILDROOT/R-hadron-1.0-1.fc25.x86_64 '!=' / ']'
+ rm -rf /home/mu/rpmbuild/BUILDROOT/R-hadron-1.0-1.fc25.x86_64
++ dirname /home/mu/rpmbuild/BUILDROOT/R-hadron-1.0-1.fc25.x86_64
+ mkdir -p /home/mu/rpmbuild/BUILDROOT
+ mkdir /home/mu/rpmbuild/BUILDROOT/R-hadron-1.0-1.fc25.x86_64
+ cd hadron-33f62c68fb29f2dfea48ba779fd23cd5570539e4
+ rm -rf /home/mu/rpmbuild/BUILDROOT/R-hadron-1.0-1.fc25.x86_64
+ mkdir -p /home/mu/rpmbuild/BUILDROOT/R-hadron-1.0-1.fc25.x86_64/usr/lib64/R/library
+ /usr/bin/R CMD INSTALL -l /home/mu/rpmbuild/BUILDROOT/R-hadron-1.0-1.fc25.x86_64/usr/lib64/R/library hadron
* installing *source* package 'hadron' ...
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gsl_sf_airy_Ai_e in -lgsl... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gsl/gsl_version.h usability... yes
checking gsl/gsl_version.h presence... yes
checking for gsl/gsl_version.h... yes
checking if GSL version >= 1.8... yes
configure: creating ./config.status
** libs
gcc -m64 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -O3 -Wall -fpic  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic  -c alpha_s.c -o alpha_s.o
gcc -m64 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -O3 -Wall -fpic  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic  -c cdh.c -o cdh.o
gcc -m64 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -O3 -Wall -fpic  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic  -c chisqrbody.c -o chisqrbody.o
chisqrbody.c: In function 'chisqrbody':
chisqrbody.c:173:44: warning: variable 'fitasqr' set but not used [-Wunused-but-set-variable]
   int i, j, N, *ij, npar, fitnnlo, fitkmf, fitasqr;
                                            ^~~~~~~
chisqrbody.c:173:36: warning: variable 'fitkmf' set but not used [-Wunused-but-set-variable]
   int i, j, N, *ij, npar, fitnnlo, fitkmf, fitasqr;
                                    ^~~~~~
chisqrbody.c:173:27: warning: variable 'fitnnlo' set but not used [-Wunused-but-set-variable]
   int i, j, N, *ij, npar, fitnnlo, fitkmf, fitasqr;
                           ^~~~~~~
chisqrbody.c:173:21: warning: variable 'npar' set but not used [-Wunused-but-set-variable]
   int i, j, N, *ij, npar, fitnnlo, fitkmf, fitasqr;
                     ^~~~
chisqrbody.c:173:17: warning: variable 'ij' set but not used [-Wunused-but-set-variable]
   int i, j, N, *ij, npar, fitnnlo, fitkmf, fitasqr;
                 ^~
gcc -m64 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -O3 -Wall -fpic  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic  -c firstPart.c -o firstPart.o
gcc -m64 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -O3 -Wall -fpic  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic  -c gen_points_array.c -o gen_points_array.o
gcc -m64 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -O3 -Wall -fpic  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic  -c gsl_fit.c -o gsl_fit.o
gsl_fit.c: In function 'multifit_cor':
gsl_fit.c:569:28: error: 'gsl_multifit_fdfsolver {aka struct <anonymous>}' has no member named 'J'
   gsl_multifit_covar(solver->J, 0.0, covar);
                            ^~
gsl_fit.c:457:26: warning: variable 'c' set but not used [-Wunused-but-set-variable]
   double * para_initial, c=1.;
                          ^
gsl_fit.c:443:18: warning: variable 'm' set but not used [-Wunused-but-set-variable]
   double p1, p2, m;
                  ^
gsl_fit.c:443:14: warning: variable 'p2' set but not used [-Wunused-but-set-variable]
   double p1, p2, m;
              ^~
gsl_fit.c:443:10: warning: variable 'p1' set but not used [-Wunused-but-set-variable]
   double p1, p2, m;
          ^~
At top level:
gsl_fit.c:434:13: warning: 'Print_State_Mass_Fit_Helper_1' defined but not used [-Wunused-function]
 static void Print_State_Mass_Fit_Helper_1(int iter, gsl_multifit_fdfsolver *solver)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib64/R/etc/Makeconf:159: recipe for target 'gsl_fit.o' failed
make: *** [gsl_fit.o] Error 1
ERROR: compilation failed for package 'hadron'
* removing '/home/mu/rpmbuild/BUILDROOT/R-hadron-1.0-1.fc25.x86_64/usr/lib64/R/library/hadron'
error: Bad exit status from /var/tmp/rpm-tmp.XN1eDL (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.XN1eDL (%install)
```

And here are the flags from GSL:

```
$ gsl-config --prefix --libs --cflags
/usr
-lgsl -lgslcblas -lm
-I/usr/include
```

It seems that they are not used, though. So perhaps there is a forward declaration used somewhere but that was not sufficient? Or my command to compile the R package is wrong (copied from the Fedora wiki)?

**Comment by kostrzewa** [comment]
Could you try the non-RPM way of installing packages?
1) create a user-local directory (but you can also install as root into
one of the system dirs) and set this directory in ~/.Renviron
my ```~/.Renviron```:
```
R_LIBS="~/local/lib/R:/usr/local/lib/R-contrib:/usr/local/lib/R/site-library:/usr/lib/R/site-library"
```
now, with the source directory for hadron in any directory, run:
```
R CMD INSTALL -l ~/${LOCALDIRSETABOVE} ${SOURCE_DIRECTORY}
```
Actually, don't bother with the above... I might know why it works for
me. I have the object file for gsl_fit lying around in this directory
from way back when I first installed hadron on my old laptop...

```
-rw-r--r-- 1 bartek bartek  50264 Mar 27  2013 gsl_fit.o
-rw-r--r-- 1 bartek bartek  68696 Mar 27  2013 gsl_multimin.o
```
So clearly there won't be a problem compiling if nothing is being
compiled...

**Comment by urbach** [comment]
I have removed the dependence on the GSL fit routines in my latest urbach/hadron master branch. Can you check, please, whether this helps?

We cannot remove the GSL dependence completely, as it is used in other places, too.

**Comment by martin-ueding** [comment]
I can now build a RPM package with it, install it and to a `library(hadron)` without a problem. The package is building here, if you are interested: https://build.opensuse.org/package/show/home:martinueding/R-hadron
